-- =====================================================================
-- V1 - initial schema for the Employee Management System.
--
-- Migrations are append-only and MUST NOT drop or recreate objects:
-- Flyway applies this exactly once per database and records the checksum.
-- To change something, add a new V<n>__ file - never edit this one.
-- =====================================================================

CREATE TABLE users (
  id            NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
  username      VARCHAR2(100) NOT NULL,
  password      VARCHAR2(200) NOT NULL,
  date_register DATE,
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_users_username UNIQUE (username)
);

CREATE TABLE employees (
  id             NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
  employee_id    VARCHAR2(50)  NOT NULL,
  full_name      VARCHAR2(200) NOT NULL,
  gender         VARCHAR2(20),
  contact_number VARCHAR2(50),
  position       VARCHAR2(100),
  image          VARCHAR2(500),
  salary         NUMBER(12)    DEFAULT 0 NOT NULL,
  insert_date    DATE,
  update_date    DATE,
  delete_date    DATE,
  status         VARCHAR2(20),
  CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE INDEX ix_employees_employee_id ON employees (employee_id);
CREATE INDEX ix_employees_status      ON employees (status, delete_date);
