-- =====================================================================
-- EmployeeManagementSystem - Oracle schema
-- Run as the application user (ems) against the FREEPDB1 pluggable DB.
-- Idempotent: drops the tables first if they already exist.
-- =====================================================================

SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR  EXIT FAILURE

BEGIN
  FOR t IN (SELECT table_name FROM user_tables
             WHERE table_name IN ('EMPLOYEES', 'USERS')) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE "' || t.table_name || '" CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

CREATE TABLE users (
  id            NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
  username      VARCHAR2(100) NOT NULL,
  password      VARCHAR2(200) NOT NULL,
  date_register DATE,
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_users_username UNIQUE (username)
);

CREATE TABLE employees (
  id             NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
  employee_id    VARCHAR2(50)  NOT NULL,
  full_name      VARCHAR2(200) NOT NULL,
  gender         VARCHAR2(20),
  contact_number VARCHAR2(50),
  position       VARCHAR2(100),
  image          VARCHAR2(500),
  salary         NUMBER(12)    DEFAULT 0 NOT NULL,
  insert_date    DATE,
  update_date    DATE,
  delete_date    DATE,
  status         VARCHAR2(20),
  CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE INDEX ix_employees_employee_id ON employees (employee_id);
CREATE INDEX ix_employees_status      ON employees (status, delete_date);

-- ---------------------------------------------------------------------
-- Seed data
-- ---------------------------------------------------------------------
INSERT INTO users (username, password, date_register) VALUES ('admin', 'admin', TRUNC(SYSDATE));

INSERT INTO employees (employee_id, full_name, gender, contact_number, position, image, salary, insert_date, status)
VALUES ('EMID-01', 'Nguyen Van A', 'Male', '0900000001', 'Developer', 'Directory\EMID-01.jpg', 1500, TRUNC(SYSDATE), 'Active');

INSERT INTO employees (employee_id, full_name, gender, contact_number, position, image, salary, insert_date, status)
VALUES ('EMID-02', 'Tran Thi B', 'Female', '0900000002', 'Manager', 'Directory\EMID-02.jpg', 2500, TRUNC(SYSDATE), 'Active');

INSERT INTO employees (employee_id, full_name, gender, contact_number, position, image, salary, insert_date, status)
VALUES ('EMID-03', 'Le Van C', 'Male', '0900000003', 'Designer', 'Directory\EMID-03.jpg', 1200, TRUNC(SYSDATE), 'Inactive');

COMMIT;

SELECT 'users: '     || COUNT(*) AS seeded FROM users;
SELECT 'employees: ' || COUNT(*) AS seeded FROM employees;

EXIT
